name = "OCAT3 SMP"
author = "LemmaEOF"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0cb9e82ab7633db24ebf4d5dee9fc6adc7c6ff03dd8071e810801028bd6edc4"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
